name: Build-Android-APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # تحديث للنسخة الرابعة

      - name: Build with Buildozer
        uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          command: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # تحديث للنسخة الرابعة لحل مشكلة deprecation
        with:
          name: Khazna-APK
          path: bin/*.apk
